# Generated by Django 5.2.4 on 2025-07-19 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('device_name', models.CharField(max_length=100)),
                ('imei_1', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('imei_2', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('device_type', models.CharField(choices=[('ANDROID', 'android'), ('IOS', 'ios')], max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('app_version', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'device_models',
                'ordering': ['-created_at'],
            },
        ),
    ]
