# Generated by Django 5.2.4 on 2025-08-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='app_version',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
