# Generated by Django 5.2.4 on 2025-07-19 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('action_type', models.TextField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('DEVICE_REGISTERED', 'Device Registered'), ('LOCATION_UPDATE', 'Location Updated'), ('PREDICTION_MADE', 'Prediction Created')], max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity_log_models',
                'ordering': ['-created_at'],
            },
        ),
    ]
