# Generated by Django 5.2.4 on 2025-08-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylogmodel',
            name='ip_address',
        ),
    ]
