# Generated by Django 5.2.4 on 2025-08-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_remove_activitylogmodel_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylogmodel',
            name='action_type',
        ),
    ]
