# Generated by Django 5.2.4 on 2025-08-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text="Is the model's object active"),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('USER', 'user')], default='user', max_length=100, null=True),
        ),
    ]
