# Generated by Django 5.2.4 on 2025-07-19 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('thana', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('signal_strength_dbm', models.FloatField(blank=True, help_text='Signal strength in dBm', null=True)),
                ('signal_quality_percent', models.FloatField(blank=True, help_text='Signal quality percentage', null=True)),
                ('latency_ms', models.FloatField(blank=True, help_text='Network latency in milliseconds', null=True)),
                ('network_type', models.CharField(blank=True, help_text='Type of network (e.g., 4G, WiFi)', max_length=50, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_location', to='device.devicemodel')),
            ],
            options={
                'db_table': 'location_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('thana', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(max_length=255)),
                ('signal_strength_dbm', models.FloatField(blank=True, help_text='Signal strength in dBm', null=True)),
                ('signal_quality_percent', models.FloatField(blank=True, help_text='Signal quality percentage', null=True)),
                ('latency_ms', models.FloatField(blank=True, help_text='Network latency in milliseconds', null=True)),
                ('network_type', models.CharField(blank=True, help_text='Type of network (e.g., 4G, WiFi)', max_length=50, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_prediction', to='device.devicemodel')),
            ],
            options={
                'db_table': 'prediction_models',
                'ordering': ['-created_at'],
            },
        ),
    ]
