# Generated by Django 5.2.4 on 2025-08-13 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_remove_devicemodel_app_version_and_more'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationmodel',
            old_name='signal_strength_dbm',
            new_name='signal_strength',
        ),
        migrations.RenameField(
            model_name='predictionmodel',
            old_name='signal_strength_dbm',
            new_name='signal_strength',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='latency_ms',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='signal_quality_percent',
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='predictionmodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='predictionmodel',
            name='division',
        ),
        migrations.RemoveField(
            model_name='predictionmodel',
            name='latency_ms',
        ),
        migrations.RemoveField(
            model_name='predictionmodel',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='predictionmodel',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='predictionmodel',
            name='signal_quality_percent',
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_location', to='device.devicemodel'),
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_predicted_location', to='device.devicemodel'),
        ),
    ]
