# Generated by Django 5.2.4 on 2025-08-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_rename_signal_strength_dbm_locationmodel_signal_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmodel',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PredictionModel',
        ),
    ]
